# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build Report

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'  # Every day at 00:00 UTC

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1.0"
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: swift build
      - name: Report
        run: swift run vps-db-tool report --db https://raw.githubusercontent.com/VirtualPinballSpreadsheet/vps-db/refs/heads/main/db/vpsdb.json
      - name: Push Report
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.COMMIT_TOKEN }}
          commit_message: "Update report"
