# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Push Test

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: date > report/date.txt
      - name: Setup Git
        run: git config --global user.email "david_koski@mac.com"; git config --global user.name "David Koski"
      - name: Setup Remote
        run: git remote set-url origin https://davidkoski:${{ secrets.COMMIT_TOKEN}}@github.com/davidkoski/vps-db-tool.git
      - name: Push
        run: git add report; git commit -m "update"; git push
      # - name: Push Report
      #   uses: devops-infra/action-commit-push@master
      #   with:
      #     github_token: ${{ secrets.COMMIT_TOKEN }}
      #     commit_message: "Update report"
